runtime: python27
api_version: 1
threadsafe: true

libraries:
  - name: ssl
    version: latest

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: main.app

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - frontend/

env_variables:
  FIREBASE_PROJECT_ID: 'trackerradio'
